version: '3.4'

services:
  hello-world:
    build:
      context: '.'
      target: hello-world
    container_name: hello_world
    volumes:
      - ./main.py:/home/sroeca/main.py
  rich-man:
    build:
      context: '.'
      target: rich-man
    container_name: rich_man
    volumes:
      - ./main.py:/home/sroeca/main.py
  nginx:
    build:
      context: '.'
      target: nginx
    ports:
      - "8000:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
